// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vccvprojmzucfyxmeagq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjY3Zwcm9qbXp1Y2Z5eG1lYWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NjUwODEsImV4cCI6MjA4NTM0MTA4MX0.o-pHCN1mI-4BmNDqiLUxaCIV3uwPR0wBgfPuPOVJZsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});